//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLUser> ALLUsers { get; set; }
        public virtual DbSet<AttemptedQuestion> AttemptedQuestions { get; set; }
        public virtual DbSet<correctAnswer> correctAnswers { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<EnrollerdCourse> EnrollerdCourses { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentAnswer> StudentAnswers { get; set; }
        public virtual DbSet<StudentAttenedence> StudentAttenedences { get; set; }
        public virtual DbSet<Studentverfication> Studentverfications { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    
        public virtual ObjectResult<getstudentQuiz_Result> getstudentQuiz()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getstudentQuiz_Result>("getstudentQuiz");
        }
    
        public virtual ObjectResult<getstudentQuizquestion_Result> getstudentQuizquestion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getstudentQuizquestion_Result>("getstudentQuizquestion");
        }
    }
}
