//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            this.AttemptedQuestions = new HashSet<AttemptedQuestion>();
            this.Questions = new HashSet<Question>();
            this.PinGenrateds = new HashSet<PinGenrated>();
        }
    
        public int Qid { get; set; }
        public string QTitle { get; set; }
        public Nullable<System.DateTime> Quizdate { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<System.TimeSpan> Startingtime { get; set; }
        public Nullable<int> QuizDuration { get; set; }
        public string CourseName { get; set; }
        public string Section { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttemptedQuestion> AttemptedQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PinGenrated> PinGenrateds { get; set; }
    }
}
