//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentverfication
    {
        public int sfid { get; set; }
        public string Picturename { get; set; }
        public Nullable<int> sid { get; set; }
    
        public virtual ALLUser ALLUser { get; set; }
    }
}
