//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswer
    {
        public int CAid { get; set; }
        public Nullable<int> Qsid { get; set; }
        public Nullable<int> Qoid { get; set; }
    
        public virtual QuestionOption QuestionOption { get; set; }
        public virtual Question Question { get; set; }
    }
}
